name: Docker Build and Release

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types: 
      - completed
    # branches:
    #     - test

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Run ID
        run: echo ${{ vars.RUN_ID }}
      - name: Get artifact id
        run: echo ${{ vars.ARTIFACT_ID }}
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ vars.RUN_ID }}
          name: jar
          github-token: ${{ secrets.MY_VARS_TOKEN }}
      - name: List files
        run: ls -lAR



