name: Docker Build and Release

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types: 
      - completed
    # branches:
    #     - test

jobs:
  release:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/download-artifact@v3
        with:
          name: jar
      - name: List files
        run: ls -lAR


